version: 2

jobs:
  test:
    docker:
      - image: circleci/node:12.18.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint commits
          command: yarn commitlint-circle

      - run:
          name: Lint codebase
          command: yarn lint && yarn format

  build_image:
    docker:
      - image: circleci/node:12.18.3

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Configure GCR access
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get install apt-transport-https
            sudo apt-get install ca-certificates gnupg
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk
            echo ${GOOGLE_AUTH} | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCP_PROJECT}
            gcloud --quiet auth configure-docker

      - run:
          name: Publish Docker image
          command: |
            export DIRTY_TAG=$(git describe --tags --always)
            export SPOKE_VERSION=${DIRTY_TAG#"v"}
            docker build --build-arg SPOKE_VERSION="$SPOKE_VERSION" --rm=false -t gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1 .
            docker tag gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1 gcr.io/spoke-rewired/spoke:$SPOKE_VERSION
            docker tag gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1 gcr.io/spoke-rewired/spoke:latest
            docker push gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1
            docker push gcr.io/spoke-rewired/spoke:$SPOKE_VERSION
            docker push gcr.io/spoke-rewired/spoke:latest

workflows:
  version: 2

  build_and_push:
    jobs:
      - test
      - build_image:
          context: gcp-spoke
          requires:
            - test
          filters:
            branches:
              only: master
